language: python
sudo: false
dist: trusty

python:
   - 3.6
   - nightly

cache: pip

env:
   - xversion=1.0 oob=1
   - xversion=1.0 oob=0
   - xversion=2.0 oob=1
   - xversion=2.0 oob=0
   - xversion=3.0 oob=1
   - xversion=3.0 oob=0

install:
   - pip install .
   - wget https://github.com/orf/xcat_app/releases/download/0.1/xcat-app-jar-with-dependencies.jar
   - wget https://github.com/orf/xcat_app/releases/download/0.1/database.xml

script:
   - java -Dorg.slf4j.simpleLogger.defaultLogLevel=warn -jar xcat-app-jar-with-dependencies.jar &
   - SERVER_PID=$!
   - SERVER=http://localhost:4567/
   - xcat --help
   - xcat detectip
   - |
    if [ "oob" = "1" ]; then
      OOB_FLAG='--oob-ip=localhost'
    fi
   - xcat $SERVER query xversion=$xversion query=Lawyer --true-string=Grisham $OOB_FLAG --features
   - xcat $SERVER query xversion=$xversion query=Lawyer --true-string=Grisham $OOB_FLAG --fast
   - xcat $SERVER query xversion=$xversion query=Lawyer --true-string=Grisham $OOB_FLAG
   - xcat $SERVER query xversion=$xversion query=Lawyer --true-string=Grisham $OOB_FLAG --cookie=abc --body=test
