language: python
sudo: required
dist: xenial
cache: pip
services: docker

python:
    - 3.7

before_install:
    - pip install --upgrade pip
    - sudo add-apt-repository ppa:duggan/bats --yes
    - sudo apt-get update -qq
    - sudo apt-get install -qq bats

install:
    - docker run --name=xcat-app -p 127.0.0.1:4567:4567 -d tomforbes/xcat-app
    - pip install .

script:
    - bats test.sh
