language: python
sudo: false
dist: trusty

python:
   - 3.6
   - nightly

cache: pip

install:
   - pip install .
   - wget https://github.com/orf/xcat_app/releases/download/0.1/xcat-app-jar-with-dependencies.jar
   - wget https://github.com/orf/xcat_app/releases/download/0.1/database.xml

script:
   - xcat detectip
   - java -jar xcat-app-jar-with-dependencies.jar --version